version: "3"
services:
  reverseproxy:
    image: udagram-reverseproxy
    ports:
      - 8080:8080
    restart: always
    depends_on:
      - backend-user
      - backend-feed
  backend-user:
    image: udagram-api-user
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:?err}
      POSTGRES_HOST: ${POSTGRES_HOST:?err}
      AWS_REGION: ${AWS_REGION:?err}
      AWS_PROFILE: ${AWS_PROFILE:?err}
      AWS_BUCKET: ${AWS_BUCKET:?err}
      JWT_SECRET: ${JWT_SECRET:?err}
      URL: ${URL:?err}
  backend-feed:
    image: udagram-api-feed
    volumes:
      - $HOME/.aws:/root/.aws
    environment:
      POSTGRES_USERNAME: ${POSTGRES_USERNAME:?err}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:?err}
      POSTGRES_DB: ${POSTGRES_DB:?err}
      POSTGRES_HOST: ${POSTGRES_HOST:?err}
      AWS_REGION: ${AWS_REGION:?err}
      AWS_PROFILE: ${AWS_PROFILE:?err}
      AWS_BUCKET: ${AWS_BUCKET:?err}
      JWT_SECRET: ${JWT_SECRET:?err}
      URL: ${URL:?err}
  frontend:
    image: udagram-frontend
    ports:
      - "8100:80"
